# CUDA/Omp translation exercise Makefile for microXOR
CC        = nvc++
OPTIMIZE  = yes
DEBUG     = no
DEVICE    = gpu
SM        = 89
GATE_ROOT ?= $(abspath ../../..)
RUN_ARGS ?= 1024 32

program = microXOR.exe
source = microXOR.cpp main.cpp
obj = $(source:.cpp=.o)

CFLAGS := $(EXTRA_CFLAGS) -std=c++17 -cuda -gpu=sm_$(SM) -Iinclude -I$(GATE_ROOT)/gate_sdk
LDFLAGS = -lcudart

ifeq ($(DEBUG),yes)
  CFLAGS += -g
  LDFLAGS += -g
endif

ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

$(program): $(obj) include/microXOR.cuh
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cpp include/microXOR.cuh
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

run: $(program)
	./$(program) $(RUN_ARGS)
