CC        = nvc++
OPTIMIZE  = yes
DEBUG     = no
SM        = 89
GATE_ROOT ?= /root/codex_baseline/cuda_omp_pareval_workdir
RUN_ARGS ?= -m event -s small -l 100000

program = XSBench
source = Main.cpp io.cpp Simulation.cpp GridInit.cpp XSutils.cpp Materials.cpp
obj = $(source:.cpp=.o)

CFLAGS := -std=c++14 -mp=gpu -gpu=sm_$(SM) -Wall -I$(GATE_ROOT)/gate_sdk
LDFLAGS = -lm

ifeq ($(DEBUG),yes)
  CFLAGS += -g -G
  LDFLAGS += -g -G
endif

ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

$(program): $(obj) XSbench_header.cuh
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cpp XSbench_header.cuh
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(program) $(obj)

run: $(program)
	./$(program) $(RUN_ARGS)
